apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-kraft.fullname" . }}-headless
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kafka-kraft.labels" . | nindent 4 }}
    service-type: headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: broker
      port: {{ .Values.ports.broker }}
      targetPort: {{ .Values.ports.broker }}
    - name: controller
      port: {{ .Values.ports.controller }}
      targetPort: {{ .Values.ports.controller }}
  selector:
    app: {{ .Values.labels.app }}
